// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public class Util
{
	public static Transform FindClosestWithTag(Transform player, string tag, Vector3 maxDistance){
		GameObject[] pickups = GameObject.FindGameObjectsWithTag("Pickup");
		Transform closest = null;
		float closestDistance = Mathf.Infinity;
		for(int ii = 0; ii < pickups.Length; ii++){
			Transform pickup = pickups[ii].transform;
			float distance = Vector3.Distance (player.position, pickup.position);
			float xDistance = Mathf.Abs (player.position.x - pickup.position.x);
			float yDistance = Mathf.Abs (player.position.y - pickup.position.y);
			float zDistance = Mathf.Abs (player.position.z - pickup.position.z);
			Debug.Log (distance + ":" + xDistance + ":" + zDistance + ":" + pickup.tag);
			if(distance < closestDistance){
				if((player.right.x > 0 && pickup.position.x < player.position.x) || (player.right.x < 0 && pickup.position.x > player.position.x)){
					if(xDistance < maxDistance.x && yDistance < maxDistance.y && zDistance < maxDistance.z){
						closest = pickup;
						closestDistance = distance;
					}
				}
			}
		}

		return closest;
	}
}
